import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { css } from "@/styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={css({
          padding: 10,
        })}
      >
        {children}
      </body>
    </html>
  );
}
